export const HeroDefaults = {
  preset: 'default' as const,
  title: 'Build Something Amazing' as const,
  subtitle:
    'Create stunning websites with our powerful platform. Start your journey today and bring your ideas to life with modern design and cutting-edge technology.' as const,
  backgroundColor: '#0f172a',
  backgroundImage: '',
  backgroundOverlay: 'rgba(15, 23, 42, 0.7)',
  textColor: '#ffffff',
  showButton: true as const,
  buttonText: 'Get Started' as const,
  buttonLink: '#' as const,
  buttonStyle: 'primary' as const,
  showSecondaryButton: true as const,
  secondaryButtonText: 'Learn More' as const,
  secondaryButtonLink: '#' as const,
  secondaryButtonStyle: 'outline' as const,
  alignment: 'center' as const,
  minHeight: '600px',
  padding: '100px 24px',
  titleSize: 'xl' as const,
  subtitleSize: 'large' as const,
  showGradient: true as const,
  gradientDirection: 'to-br' as const,
  gradientColors: '#667eea, #764ba2, #f093fb',
  animation: 'fade-in' as const,
  borderRadius: '0px',
  shadow: 'xl' as const,
}
