import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { OpenAPI } from "@/client";
import { getSession } from "@/lib/session-utils";
import { cn } from "@/lib/utils";

OpenAPI.BASE = process.env.NEXT_PUBLIC_API_URL!;

OpenAPI.interceptors.request.use(async (options) => {
  const session = await getSession();
  options.headers = {
    ...options.headers,
    Authorization: `Bearer ${session.access_token}`,
    __tenant: session.tenantId ?? "",
  };
  return options;
});


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
