import { CarouselBlockProps } from './CarouselBlockProps'

export const CarouselBlockDefaults: CarouselBlockProps = {
  slides: [
    {
      id: '1',
      imageUrl: 'https://picsum.photos/1200/600?random=1',
      title: 'Welcome to Our Platform',
      description: 'Discover amazing features and possibilities with our innovative solution.',
      buttonText: 'Get Started',
      buttonUrl: '#',
      backgroundColor: '#000000',
      textColor: '#ffffff',
      textAlignment: 'center',
      overlayOpacity: 0.3,
    },
    {
      id: '2',
      imageUrl: 'https://picsum.photos/1200/600?random=2',
      title: 'Powerful Features',
      description: 'Experience the power of our advanced features designed for modern needs.',
      buttonText: 'Learn More',
      buttonUrl: '#',
      backgroundColor: '#1f2937',
      textColor: '#ffffff',
      textAlignment: 'left',
      overlayOpacity: 0.4,
    },
    {
      id: '3',
      imageUrl: 'https://picsum.photos/1200/600?random=3',
      title: 'Seamless Integration',
      description: 'Integrate effortlessly with your existing workflow and tools.',
      buttonText: 'Try Now',
      buttonUrl: '#',
      backgroundColor: '#374151',
      textColor: '#ffffff',
      textAlignment: 'right',
      overlayOpacity: 0.5,
    },
  ],
  autoPlay: true,
  autoPlayInterval: 5000,
  showArrows: true,
  showDots: true,
  loop: true,
  pauseOnHover: true,
  height: '400px',
  width: '100%',
  maxWidth: '100%',
  padding: '0',
  borderRadius: '8px',
  shadow: false,
  arrowColor: '#ffffff',
  arrowBackgroundColor: 'rgba(0, 0, 0, 0.5)',
  dotColor: 'rgba(255, 255, 255, 0.5)',
  dotActiveColor: '#ffffff',
  responsive: {
    mobile: {
      height: '300px',
      showArrows: false,
      showDots: true,
    },
    tablet: {
      height: '350px',
      showArrows: true,
      showDots: true,
    },
    desktop: {
      height: '400px',
      showArrows: true,
      showDots: true,
    },
  },
} 